### ISSUE TITLE
I don't see the product in the install form

### ISSUE THREAD

**Issue by keul** [collective/collective.pfg.soup#3]
I didn't find any time to investigate this, but:
 * I see the product in the list of eggs of my buildout
 * All dependencies are downloaded
However I don't see the product in the install add-ons form, neither I see the profile in the portal_setup.

This on Plone 4.2.5 and 4.3.1.

**Comment by chlarsen** [comment]
Dear All,
The addition of collective.pfg.soup to zcml does the trick. Seems the automagical inclusion does not work. Thanks a lot for your help! 
Chris

**Comment by agitator** [comment]
fixed within master, namespace_packages=['collective'] was missing in setup.py
